<a href="https://colab.research.google.com/github/satyam1459/Numpy/blob/main/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

NumPy is the fundamental package for scientific computing with Python.

•	A powerful N-dimensional array object

•	Sophisticated (broadcasting) functions

•	Tools for integrating C/C++ and Fortan code.

•	Useful linear algebra, Fourier transform etc





In [2]:
# NUMPY
import numpy as np
import sys

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4])

In [5]:
b = np.array([0,.5,1,1.5,2])

In [7]:
a[0], a[1]

(1, 2)

In [8]:
b[0], b[1]

(0.0, 0.5)

In [9]:
a[0:]

array([1, 2, 3, 4])

In [10]:
a[0:2]

array([1, 2])

In [12]:
a[1:-1]

array([2, 3])

In [14]:
#In NumPy, a[::2] is a slicing operation that selects every other element from the array a, starting from the first element.
a[::2]

array([1, 3])

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b[0], b[2], b[-1]

array([0., 1., 2.])

In [18]:
# Multi-indexing
b[[0,2,-1]]

array([0., 1., 2.])

**Array Types**

In [19]:
a

array([1, 2, 3, 4])

In [21]:
# 64 is by deafault size of numpy int array
a.dtype

dtype('int64')

In [22]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [23]:
b.dtype

dtype('float64')

In [26]:
np.array([1,2,3,4], dtype = float)

array([1., 2., 3., 4.])

In [28]:
np.array([1,2,3,4], dtype = np.int8)

array([1, 2, 3, 4], dtype=int8)

In [29]:
c = np.array(['a', 'b', 'c'])

NumPy arrays are designed to efficiently store and manipulate homogeneous numerical data, such as integers and floating-point numbers. While it's possible to create arrays with dtype numpy.character, NumPy arrays aren't particularly optimized for storing characters or strings.

In [32]:
c.dtype

dtype('<U1')

In [31]:
d = np.array([{'a': 1},sys])

In [33]:
d.dtype

dtype('O')

**Dimensions and shapes**

We can create multi dimensional arrays i.e, matrices

In [34]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [35]:
A.shape

(2, 3)

In [36]:
A.ndim

2

In [37]:
# total size of elements
A.size

6

In [39]:
B = np.array([
    [
       [12,11,10],
       [9, 8, 7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
])

In [40]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [42]:
B.shape

(2, 2, 3)

In [43]:
B.ndim

3

In [44]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects

In [46]:
C = np.array([
    [
       [12,11,10],
       [9, 8, 7],
    ],
    [
        [6,5,4]
    ]
])

<ipython-input-46-08e60c25bf9a>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [47]:
C.dtype

dtype('O')

In [48]:
C.shape

(2,)

In [49]:
C.size

2

In [50]:
type(C[0])

list

**Indexing and Slicing of Matrices**

In [51]:
# Square Matrix
A = np.array([
# 0 . 1 . 2
  [1,2,3],
  [4,5,6],
  [7,8,9]
] )

In [52]:
A[1]

array([4, 5, 6])

In [53]:
# select second row, first element
A[1] [0]

4

In [55]:
# A[d1, d2, d3, d4]
A[1,0]

4

In [56]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
A[:,2]

array([3, 6, 9])

In [58]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [59]:
A[:2,2]

array([3, 6])

In [60]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
A[1] = np.array([10,10,10])

In [62]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [63]:
A[2] = 99

In [64]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

**Summary statistics**

In [65]:
a = np.array([1,2,3,4])

In [66]:
a.sum()

10

In [67]:
a.mean()

2.5

In [68]:
a.std()

1.118033988749895

In [69]:
a.var()

1.25

In [70]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [71]:
A.sum()

45

In [72]:
A.mean()

5.0

In [73]:
A.std()

2.581988897471611

In [76]:
# here axis is over dimension
A.sum(axis=0)

array([12, 15, 18])

In [75]:
A.sum(axis=1)

array([ 6, 15, 24])

In [77]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])